export const questions = [
    {
        id: 1,
        type: 'introversion',
        text: 'Do you prefer spending time alone or with a small group of people rather than being in large social gatherings?',
        answers: [
            { text: 'Strongly Agree', value: 3 },
            { text: 'Agree', value: 2 },
            { text: 'Neutral', value: 1 },
            { text: 'Disagree', value: -2 },
            { text: 'Strongly Disagree', value: -3 },
        ],
    },
    {
        id: 2,
        type: 'introversion',
        text: 'Do you feel drained or exhausted after spending time in large groups or social situations?',
        answers: [
            { text: 'Strongly Agree', value: 3 },
            { text: 'Agree', value: 2 },
            { text: 'Neutral', value: 1 },
            { text: 'Disagree', value: -2 },
            { text: 'Strongly Disagree', value: -3 },
        ],
    },
    {
        id: 3,
        type: 'introversion',
        text: 'Do you find it easier to express yourself through writing or other solitary activities rather than speaking in front of others?',
        answers: [
            { text: 'Strongly Agree', value: 3 },
            { text: 'Agree', value: 2 },
            { text: 'Neutral', value: 1 },
            { text: 'Disagree', value: -2 },
            { text: 'Strongly Disagree', value: -3 },
        ],
    },
    {
        id: 4,
        type: 'introversion',
        text: 'Do you often take time to think before speaking or acting, rather than being spontaneous or jumping into action?',
        answers: [
           { text: 'Strongly Agree', value: 3 },
            { text: 'Agree', value: 2 },
            { text: 'Neutral', value: 1 },
            { text: 'Disagree', value: -2 },
            { text: 'Strongly Disagree', value: -3 },
        ],
    },
    {
        id: 5,
        type: 'introversion',
        text: 'Do you sometimes feel like you need to recharge by being alone after a long day or social event?',
        answers: [
            { text: 'Strongly Agree', value: 3 },
            { text: 'Agree', value: 2 },
            { text: 'Neutral', value: 1 },
            { text: 'Disagree', value: -2 },
            { text: 'Strongly Disagree', value: -3 },
        ],
    },
    {
        id: 6,
        type: 'intuition',
        text: 'Do you often think about the future and the possibilities it holds?',
        answers: [
            { text: 'Strongly Agree', value: 3 },
            { text: 'Agree', value: 2 },
            { text: 'Neutral', value: 1 },
            { text: 'Disagree', value: -2 },
            { text: 'Strongly Disagree', value: -3 },
        ],
    },
    {
        id: 7,
        type: 'intuition',
        text: 'Do you like to approach problems in a creative or unconventional way?',
        answers: [
           { text: 'Strongly Agree', value: 3 },
            { text: 'Agree', value: 2 },
            { text: 'Neutral', value: 1 },
            { text: 'Disagree', value: -2 },
            { text: 'Strongly Disagree', value: -3 },
        ],
    },
    {
        id: 8,
        type: 'intuition',
        text: 'Do you enjoy exploring new ideas and concepts, even if they are not immediately practical?',
        answers: [
            { text: 'Strongly Agree', value: 3 },
            { text: 'Agree', value: 2 },
            { text: 'Neutral', value: 1 },
            { text: 'Disagree', value: -2 },
            { text: 'Strongly Disagree', value: -3 },
        ],
    },
    {
        id: 9,
        type: 'intuition',
        text: 'Do you often rely on your intuition or gut feeling when making decisions?',
        answers: [
            { text: 'Strongly Agree', value: 3 },
            { text: 'Agree', value: 2 },
            { text: 'Neutral', value: 1 },
            { text: 'Disagree', value: -2 },
            { text: 'Strongly Disagree', value: -3 },
        ],
    },
    {
        id: 10,
        type: 'intuition',
        text: 'Do you find it more interesting to imagine what could be rather than focus on what is?',
        answers: [
            { text: 'Strongly Agree', value: 3 },
            { text: 'Agree', value: 2 },
            { text: 'Neutral', value: 1 },
            { text: 'Disagree', value: -2 },
            { text: 'Strongly Disagree', value: -3 },
        ],
    },
    {
        id: 11,
        type: 'thinking',
        text: 'Do you prioritize rationality and logic over emotions when making decisions?',
        answers: [
            { text: 'Strongly Agree', value: 3 },
            { text: 'Agree', value: 2 },
            { text: 'Neutral', value: 1 },
            { text: 'Disagree', value: -2 },
            { text: 'Strongly Disagree', value: -3 },
        ],
    },
    {
        id: 12,
        type: 'thinking',
        text: 'Do you prefer to analyze and understand the underlying principles of things rather than simply memorize them?',
        answers: [
            { text: 'Strongly Agree', value: 3 },
            { text: 'Agree', value: 2 },
            { text: 'Neutral', value: 1 },
            { text: 'Disagree', value: -2 },
            { text: 'Strongly Disagree', value: -3 },
        ],
    },
    {
        id: 13,
        type: 'thinking',
        text: 'Do you find it more important to be truthful or tactful when giving feedback or criticism?',
        answers: [
           { text: 'Strongly Agree', value: 3 },
            { text: 'Agree', value: 2 },
            { text: 'Neutral', value: 1 },
            { text: 'Disagree', value: -2 },
            { text: 'Strongly Disagree', value: -3 },
        ],
    },
    {
        id: 14,
        type: 'thinking',
        text: 'Do you enjoy debating and challenging others’ ideas or opinions?',
        answers: [
            { text: 'Strongly Agree', value: 3 },
            { text: 'Agree', value: 2 },
            { text: 'Neutral', value: 1 },
            { text: 'Disagree', value: -2 },
            { text: 'Strongly Disagree', value: -3 },
        ],
    },
    {
        id: 15,
        type: 'thinking',
        text: 'Do you rely on reason and evidence over intuition or personal experience when forming opinions or beliefs?',
        answers: [
            { text: 'Strongly Agree', value: 3 },
            { text: 'Agree', value: 2 },
            { text: 'Neutral', value: 1 },
            { text: 'Disagree', value: -2 },
            { text: 'Strongly Disagree', value: -3 },
        ],
    },
    {
        id: 16,
        type: 'judging',
        text: 'Do you prefer to have a schedule or plan for your day rather than just going with the flow?',
        answers: [
            { text: 'Strongly Agree', value: 3 },
            { text: 'Agree', value: 2 },
            { text: 'Neutral', value: 1 },
            { text: 'Disagree', value: -2 },
            { text: 'Strongly Disagree', value: -3 },
        ],
    },
    {
        id: 17,
        type: 'judging',
        text: 'Do you typically like to make decisions quickly rather than taking time to consider all the options?',
        answers: [
            { text: 'Strongly Agree', value: 3 },
            { text: 'Agree', value: 2 },
            { text: 'Neutral', value: 1 },
            { text: 'Disagree', value: -2 },
            { text: 'Strongly Disagree', value: -3 },
        ],
    },
    {
        id: 18,
        type: 'judging',
        text: 'Do you feel more comfortable when things are decided and settled rather than up in the air?',
        answers: [
            { text: 'Strongly Agree', value: 3 },
            { text: 'Agree', value: 2 },
            { text: 'Neutral', value: 1 },
            { text: 'Disagree', value: -2 },
            { text: 'Strongly Disagree', value: -3 },
        ],
    },
    {
        id: 19,
        type: 'judging',
        text: 'Do you like to plan ahead for events or trips rather than leaving things to chance?',
        answers: [
            { text: 'Strongly Agree', value: 3 },
            { text: 'Agree', value: 2 },
            { text: 'Neutral', value: 1 },
            { text: 'Disagree', value: -2 },
            { text: 'Strongly Disagree', value: -3 },
        ],
    },
    {
        id: 20,
        type: 'judging',
        text: 'Do you tend to be very organized in your daily life and environment?',
        answers: [
            { text: 'Strongly Agree', value: 3 },
            { text: 'Agree', value: 2 },
            { text: 'Neutral', value: 1 },
            { text: 'Disagree', value: -2 },
            { text: 'Strongly Disagree', value: -3 },
        ],
    }
]